[2023-10-19T12:43:44.174+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.load_data_to_mongo scheduled__2021-05-02T00:00:00+00:00 [queued]>
[2023-10-19T12:43:44.187+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.load_data_to_mongo scheduled__2021-05-02T00:00:00+00:00 [queued]>
[2023-10-19T12:43:44.187+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-19T12:43:44.213+0000] {taskinstance.py:1382} INFO - Executing <Task(DockerOperator): load_data_to_mongo> on 2021-05-02 00:00:00+00:00
[2023-10-19T12:43:44.229+0000] {standard_task_runner.py:57} INFO - Started process 1158 to run task
[2023-10-19T12:43:44.236+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'load_data_to_mongo', 'scheduled__2021-05-02T00:00:00+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmppvq7h5qw']
[2023-10-19T12:43:44.238+0000] {standard_task_runner.py:85} INFO - Job 247: Subtask load_data_to_mongo
[2023-10-19T12:43:44.386+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.load_data_to_mongo scheduled__2021-05-02T00:00:00+00:00 [running]> on host 6f5df7fea6fd
[2023-10-19T12:43:44.571+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='load_data_to_mongo' AIRFLOW_CTX_EXECUTION_DATE='2021-05-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-05-02T00:00:00+00:00'
[2023-10-19T12:43:44.601+0000] {docker.py:337} INFO - Starting docker container from image python/pandas:1.0.0
[2023-10-19T12:43:45.478+0000] {docker.py:406} INFO - Traceback (most recent call last):
  File "/opt/pandasapp/script/load_to_mongo.py", line 22, in <module>
    file_data = json.load(f)
  File "/usr/local/lib/python3.10/json/__init__.py", line 293, in load
[2023-10-19T12:43:45.479+0000] {docker.py:406} INFO - return loads(fp.read(),
[2023-10-19T12:43:45.480+0000] {docker.py:406} INFO - File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
[2023-10-19T12:43:45.480+0000] {docker.py:406} INFO - return _default_decoder.decode(s)
[2023-10-19T12:43:45.481+0000] {docker.py:406} INFO - File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
[2023-10-19T12:43:45.481+0000] {docker.py:406} INFO - obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[2023-10-19T12:43:45.481+0000] {docker.py:406} INFO - File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
[2023-10-19T12:43:45.481+0000] {docker.py:406} INFO - raise JSONDecodeError("Expecting value", s, err.value) from None
[2023-10-19T12:43:45.481+0000] {docker.py:406} INFO - json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2023-10-19T12:43:46.336+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 479, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 354, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 414, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2023-10-19T12:43:46.342+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=copy_tranform_to_mongo, task_id=load_data_to_mongo, execution_date=20210502T000000, start_date=20231019T124344, end_date=20231019T124346
[2023-10-19T12:43:46.379+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 247 for task load_data_to_mongo (Docker container failed: {'StatusCode': 1}; 1158)
[2023-10-19T12:43:46.401+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-19T12:43:46.573+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
