[2023-10-19T13:47:48.094+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.load_data_to_mongo manual__2023-10-19T13:47:39.519696+00:00 [queued]>
[2023-10-19T13:47:48.100+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.load_data_to_mongo manual__2023-10-19T13:47:39.519696+00:00 [queued]>
[2023-10-19T13:47:48.100+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-19T13:47:48.108+0000] {taskinstance.py:1382} INFO - Executing <Task(DockerOperator): load_data_to_mongo> on 2023-10-19 13:47:39.519696+00:00
[2023-10-19T13:47:48.112+0000] {standard_task_runner.py:57} INFO - Started process 984 to run task
[2023-10-19T13:47:48.114+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'load_data_to_mongo', 'manual__2023-10-19T13:47:39.519696+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmprvpqzy4r']
[2023-10-19T13:47:48.115+0000] {standard_task_runner.py:85} INFO - Job 104: Subtask load_data_to_mongo
[2023-10-19T13:47:48.147+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.load_data_to_mongo manual__2023-10-19T13:47:39.519696+00:00 [running]> on host f2b9ba520501
[2023-10-19T13:47:48.195+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='load_data_to_mongo' AIRFLOW_CTX_EXECUTION_DATE='2023-10-19T13:47:39.519696+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-19T13:47:39.519696+00:00'
[2023-10-19T13:47:48.207+0000] {docker.py:337} INFO - Starting docker container from image python/pandas:1.0.0
[2023-10-19T13:47:48.511+0000] {docker.py:406} INFO - Traceback (most recent call last):
  File "/opt/pandasapp/script/load_to_mongo.py", line 9, in <module>
    client = pymongo.MongoClient('mongo:27017/')#username='root', password='example')
  File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 766, in __init__
[2023-10-19T13:47:48.512+0000] {docker.py:406} INFO - res = uri_parser.parse_uri(
  File "/usr/local/lib/python3.10/site-packages/pymongo/uri_parser.py", line 496, in parse_uri
[2023-10-19T13:47:48.512+0000] {docker.py:406} INFO - raise InvalidURI(f"Invalid URI scheme: URI must begin with '{SCHEME}' or '{SRV_SCHEME}'")
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
[2023-10-19T13:47:48.693+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 479, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 354, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 414, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2023-10-19T13:47:48.695+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=copy_tranform_to_mongo, task_id=load_data_to_mongo, execution_date=20231019T134739, start_date=20231019T134748, end_date=20231019T134748
[2023-10-19T13:47:48.702+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 104 for task load_data_to_mongo (Docker container failed: {'StatusCode': 1}; 984)
[2023-10-19T13:47:48.728+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-19T13:47:48.752+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
