[2023-10-17T11:14:47.833+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-01-15T00:00:00+00:00 [queued]>
[2023-10-17T11:14:47.839+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-01-15T00:00:00+00:00 [queued]>
[2023-10-17T11:14:47.839+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-17T11:14:47.848+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-01-15 00:00:00+00:00
[2023-10-17T11:14:47.855+0000] {standard_task_runner.py:57} INFO - Started process 385 to run task
[2023-10-17T11:14:47.857+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-01-15T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmpaddmijwi']
[2023-10-17T11:14:47.857+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask waiting_for_data
[2023-10-17T11:14:47.891+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-01-15T00:00:00+00:00 [running]> on host 238c1d4ff767
[2023-10-17T11:14:47.940+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-01-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-01-15T00:00:00+00:00'
[2023-10-17T11:14:47.947+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-10-17T11:14:47.947+0000] {filesystem.py:64} INFO - Poking for file /opt/in/in/tiktok_google_play_reviews.csv
[2023-10-17T11:15:48.015+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-10-17T11:15:48.016+0000] {filesystem.py:64} INFO - Poking for file /opt/in/in/tiktok_google_play_reviews.csv
[2023-10-17T11:16:48.081+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-10-17T11:16:48.081+0000] {filesystem.py:64} INFO - Poking for file /opt/in/in/tiktok_google_play_reviews.csv
[2023-10-17T11:17:48.152+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-10-17T11:17:48.152+0000] {filesystem.py:64} INFO - Poking for file /opt/in/in/tiktok_google_play_reviews.csv
[2023-10-17T11:18:48.219+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-10-17T11:18:48.219+0000] {filesystem.py:64} INFO - Poking for file /opt/in/tiktok_google_play_reviews.csv
[2023-10-17T11:18:48.219+0000] {filesystem.py:69} INFO - Found File /opt/in/tiktok_google_play_reviews.csv last modified: 20220405221612
[2023-10-17T11:18:48.220+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-10-17T11:18:48.229+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210115T000000, start_date=20231017T111447, end_date=20231017T111848
[2023-10-17T11:18:48.262+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-17T11:18:48.275+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-18T10:42:11.457+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-01-15T00:00:00+00:00 [queued]>
[2023-10-18T10:42:11.469+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-01-15T00:00:00+00:00 [queued]>
[2023-10-18T10:42:11.469+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-18T10:42:11.508+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-01-15 00:00:00+00:00
[2023-10-18T10:42:11.513+0000] {standard_task_runner.py:57} INFO - Started process 1418 to run task
[2023-10-18T10:42:11.516+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-01-15T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmpx1mtt81a']
[2023-10-18T10:42:11.517+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask waiting_for_data
[2023-10-18T10:42:11.560+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-01-15T00:00:00+00:00 [running]> on host 2473b23ba069
[2023-10-18T10:42:11.618+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-01-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-01-15T00:00:00+00:00'
[2023-10-18T10:42:11.637+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 257, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 239, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/filesystem.py", line 61, in poke
    hook = FSHook(self.fs_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/filesystem.py", line 38, in __init__
    conn = self.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `fs_default` isn't defined
[2023-10-18T10:42:11.641+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210115T000000, start_date=20231018T104211, end_date=20231018T104211
[2023-10-18T10:42:11.655+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 18 for task waiting_for_data (The conn_id `fs_default` isn't defined; 1418)
[2023-10-18T10:42:11.689+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-18T10:42:11.715+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-18T11:14:41.411+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-01-15T00:00:00+00:00 [queued]>
[2023-10-18T11:14:41.418+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-01-15T00:00:00+00:00 [queued]>
[2023-10-18T11:14:41.418+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-18T11:14:41.431+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-01-15 00:00:00+00:00
[2023-10-18T11:14:41.436+0000] {standard_task_runner.py:57} INFO - Started process 123 to run task
[2023-10-18T11:14:41.439+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-01-15T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmpggd6jq8s']
[2023-10-18T11:14:41.440+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask waiting_for_data
[2023-10-18T11:14:41.479+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-01-15T00:00:00+00:00 [running]> on host 0e68aa52dfc7
[2023-10-18T11:14:41.537+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-01-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-01-15T00:00:00+00:00'
[2023-10-18T11:14:41.550+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 257, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 239, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/filesystem.py", line 61, in poke
    hook = FSHook(self.fs_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/filesystem.py", line 38, in __init__
    conn = self.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `fs_default` isn't defined
[2023-10-18T11:14:41.553+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210115T000000, start_date=20231018T111441, end_date=20231018T111441
[2023-10-18T11:14:41.562+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 17 for task waiting_for_data (The conn_id `fs_default` isn't defined; 123)
[2023-10-18T11:14:41.570+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-18T11:14:41.595+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-19T12:09:53.785+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-01-15T00:00:00+00:00 [queued]>
[2023-10-19T12:09:53.796+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-01-15T00:00:00+00:00 [queued]>
[2023-10-19T12:09:53.796+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-19T12:09:53.848+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-01-15 00:00:00+00:00
[2023-10-19T12:09:53.858+0000] {standard_task_runner.py:57} INFO - Started process 187 to run task
[2023-10-19T12:09:53.862+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-01-15T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmp6q9yzysj']
[2023-10-19T12:09:53.863+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask waiting_for_data
[2023-10-19T12:09:53.911+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-01-15T00:00:00+00:00 [running]> on host 6f5df7fea6fd
[2023-10-19T12:09:53.975+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-01-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-01-15T00:00:00+00:00'
[2023-10-19T12:09:53.990+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 257, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 239, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/filesystem.py", line 61, in poke
    hook = FSHook(self.fs_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/filesystem.py", line 38, in __init__
    conn = self.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `fs_default` isn't defined
[2023-10-19T12:09:53.993+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210115T000000, start_date=20231019T120953, end_date=20231019T120953
[2023-10-19T12:09:54.002+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 17 for task waiting_for_data (The conn_id `fs_default` isn't defined; 187)
[2023-10-19T12:09:54.037+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-19T12:09:54.061+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-19T13:03:25.631+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-01-15T00:00:00+00:00 [queued]>
[2023-10-19T13:03:25.659+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-01-15T00:00:00+00:00 [queued]>
[2023-10-19T13:03:25.660+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-19T13:03:25.692+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-01-15 00:00:00+00:00
[2023-10-19T13:03:25.714+0000] {standard_task_runner.py:57} INFO - Started process 161 to run task
[2023-10-19T13:03:25.718+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-01-15T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmpnv5kqxam']
[2023-10-19T13:03:25.728+0000] {standard_task_runner.py:85} INFO - Job 28: Subtask waiting_for_data
[2023-10-19T13:03:25.879+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-01-15T00:00:00+00:00 [running]> on host f2b9ba520501
[2023-10-19T13:03:26.163+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-01-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-01-15T00:00:00+00:00'
[2023-10-19T13:03:26.201+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-10-19T13:03:26.202+0000] {filesystem.py:64} INFO - Poking for file /opt/in/tiktok_google_play_reviews.csv
[2023-10-19T13:03:26.202+0000] {filesystem.py:69} INFO - Found File /opt/in/tiktok_google_play_reviews.csv last modified: 20220405221612
[2023-10-19T13:03:26.202+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-10-19T13:03:26.220+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210115T000000, start_date=20231019T130325, end_date=20231019T130326
[2023-10-19T13:03:26.282+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-19T13:03:26.389+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
